import { v4 as uuidv4 } from "uuid";
function radioStations() {
  return [
    {
      name: "Top FM",
      cover: "https://cdn-profiles.tunein.com/s17641/images/logog.jpg?t=158352",
      location: "Belgrade, Serbia",
      audio: "https://topfm64ssl.streaming.rs:9287/;stream.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Naxi Radio",
      cover: "https://cdn-profiles.tunein.com/s9208/images/logog.png?t=160226",
      location: "Belgrade, Serbia",
      audio: "https://naxi64ssl.streaming.rs:9162/;stream.nsv",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "PLAY",
      cover:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2M_K7U7jFWm0GW4M2Lj0GzHIA0ILHN9n-iA&usqp=CAU",
      location: "Belgrade, Serbia",
      audio: "http://stream.playradio.rs:8001/play.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
       
    {
      name: "Radio S1",
      cover:
        "https://pbs.twimg.com/profile_images/680388582792654849/7ubKPbYv_400x400.png",
      location: "Belgrade, Serbia",
      audio: "https://stream.radios.rs:9000/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio S2",
      cover:
        "https://pbs.twimg.com/profile_images/680307817610268672/0ldxdZKM.png",
      location: "Belgrade, Serbia",
      audio: "https://stream.radios.rs:9002/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio S3",
      cover:
        "https://pbs.twimg.com/profile_images/1044925841765994496/WhsBsKwP_400x400.jpg",
      location: "Belgrade, Serbia",
      audio: "https://stream.radios.rs:9004/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio S4",
      cover:
        "https://pbs.twimg.com/profile_images/1044926351340433409/VaBq4R2w.jpg",
      location: "Belgrade, Serbia",
      audio: "https://stream.radios.rs:9006/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Hit FM",
      cover: "https://player.hitfm.rs/images/hitfm.jpg",
      location: "Serbia",
      audio: "https://streaming.hitfm.rs/hit.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio JAT",
      cover: "http://player.radiojat.rs/images/radiojat-beograd.jpg",
      location: "Belgrade, Serbia",
      audio: "https://streaming.radiojat.rs/radiojat.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Red",
      cover:
        "https://www.uzivoradio.net/wp-content/uploads/2020/11/red-beograd.jpg",
      location: "Belgrade, Serbia",
      audio: "https://stream.redradio.rs/sid=1/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Rock Radio 96.2",
      cover:
        "https://pbs.twimg.com/profile_images/1247111016019832832/mmC0Jix0_400x400.jpg",
      location: "Serbia",
      audio: "https://mastermedia.shoutca.st/proxy/rockradio?mp=/stream",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Karolina",
      cover: "https://player.karolina.rs/images/karolina-beograd.jpg",
      location: "Belgrade, Serbia",
      audio: "https://streaming.karolina.rs/karolina.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Nostalgie",
      cover: "https://nostalgija.rs/player/skin/radio/play.svg",
      location: "Belgrade, Serbia",
      audio: "https://nostalgie64ssl.streaming.rs:9262/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "TDI ",
      cover:
        "https://yt3.ggpht.com/ytc/AAUvwnhPif7if3GJog7B0m7vkaf3e2HMNKWtlatJZX-Zgg=s900-c-k-c0x00ffffff-no-rj",
      location: "Belgrade, Serbia",
      audio: "https://streaming.tdiradio.com/tdiradio.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio IN",
      cover:
        "https://www.radioinbeograd.rs/wp-content/uploads/2020/09/Radio-IN-480x320.png",
      location: "Belgrade, Serbia",
      audio: "http://radio3-128.streaming.rs:9200/;stream.nsv",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Pink",
      cover:
        "https://lampert.at/files/uploads/Sender/133-2124_bis_24-12-2016.png",
      location: "Belgrade, Serbia",
      audio: "http://pink.exyuserver.com/;stream.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Bum Bum Radio",
      cover:
        "http://bumbumradio.rs/wp-content/uploads/2017/06/bumbumradiologo.png",
      location: "Belgrade, Serbia",
      audio: "http://bumbum-stream.netlogic.rs:8000/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Ritam Srca",
      cover:
        "https://mytuner.global.ssl.fastly.net/media/tvos_radios/sjxm5veqjlug.jpg",
      location: "Belgrade, Serbia",
      audio: "http://51.75.146.35:8008/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "OK Radio",
      cover:
        "https://dbs.radioline.fr/pictures/radio_e055db5555c2d4e51f1db677eed00f2a/logo200.jpg?size=200",
      location: "Belgrade, Serbia",
      audio: "http://live.okradio.net:8020/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Belle Amie Nis",
      cover: "http://guzei.com/online_radio/logo300/15963.jpg",
      location: "Nis, Serbia",
      audio: "http://92.60.230.200:5040/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "021",
      cover:
        "https://pbs.twimg.com/profile_images/1241688307576311808/zIVl__4J_400x400.jpg",
      location: "Novi Sad, Serbia",
      audio: "http://109.206.96.106:8000/;*.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Prvi Radio",
      cover:
        "https://radiostanice.co/sites/default/files/radio/logos/logo-prvi-radio-novi-sad.jpg",
      location: "Novi Sad, Serbia",
      audio: "https://mastermedia.shoutca.st/proxy/prviradions?mp=/stream",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "AS FM",
      cover:
        "https://pbs.twimg.com/profile_images/559995699832438784/XW5xHHeF_400x400.jpeg",
      location: "Novi Sad, Serbia",
      audio: "https://mastermedia.shoutca.st/proxy/radioasfm?mp=/stream",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Naxi  Ex Yu",
      cover: "http://m.naxi.rs/exyu/logo.png",
      location: "Internet Radio",
      audio: "https://naxidigital-exyu128ssl.streaming.rs:8242/;stream.nsv",
      country: "srb",
      id: uuidv4(),
      active: true,
    },
    {
      name: "Naxi Boem",
      cover: "http://m.naxi.rs/boem/logo.png",
      location: "Internet Radio",
      audio: "http://naxidigital-boem128.streaming.rs:8160/;stream.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Naxi 80te",
      cover: "http://m.naxi.rs/80e/logo.png",
      location: "Internet Radio",
      audio: "https://naxidigital-80s128ssl.streaming.rs:8042/;stream.nsv",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Naxi 90te",
      cover:
        "http://www.exyuradio.net/pub/catalog/naxi-90te-radio-beograd-uzivo.jpg",
      location: "Internet Radio",
      audio: "https://naxidigital-90s128ssl.streaming.rs:8282/;stream.nsv",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Naxi Gold",
      cover:
        "https://lh3.googleusercontent.com/proxy/Jv9UWrfeYZ_IgCoTpv3VWFIee3kle24QlNtpO5xF4ssQYgirzQV4GT5gYRg1rmEsxoLwCZv9",
      location: "Internet Radio",
      audio: "https://naxidigital-gold128ssl.streaming.rs:8062/;stream.nsv",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Naxi Rock",
      cover: "http://m.naxi.rs/rock/logo.png",
      location: "Internet Radio",
      audio: "https://naxidigital-rock128ssl.streaming.rs:8182/;stream.nsv",
      country: "srb",
      id: uuidv4(),
      active: false,
    },

    {
      name: "Naxi Love",
      cover:
        "https://lh3.googleusercontent.com/proxy/pBHkTSPV3BzoaPGvWhHPa-zz9uAX_ZfPRezN8PltmegMmxYugIuM_MYUwogcaY7plsX4N7BR",
      location: "Internet Radio",
      audio: "https://naxidigital-love128ssl.streaming.rs:8102/;stream.nsv",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "PLAY Soft",
      cover:
        "https://lh3.googleusercontent.com/proxy/5nBvCtub4Yb82j-UIz1CR-Q1hab8FcdPREgm16GIXdzyNv7LzqFN17OAaxxGsX3vHZXzf1xLWMxgK5UNSri7S4wSEfwGLoVIYTnXtdijWZdlI_L1JlA_lA",
      location: "Belgrade, Serbia",
      audio: " https://stream.playradio.rs:8443/soft.mp3",
      country: "srb",
      id: uuidv4(),
      active: false,
    },
    {
      name: "narodni",
      cover:
        "https://yt3.ggpht.com/ytc/AAUvwnipsvcIvo_TJdnwvlzwIys3e_4WyGa8-Fv5nG9XKQ=s900-c-k-c0x00ffffff-no-rj",
      location: "Zagreb, Croatia",
      audio: "http://live.narodni.hr:8059/stream",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Antena ZG",
      cover:
        "https://mytuner.global.ssl.fastly.net/media/tvos_radios/uVn5WkCm3y.png",
      location: "Zagreb, Croatia",
      audio: "http://live.antenazagreb.hr:8000/;stream.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Otvoreni radio",
      cover:
        "https://mytuner.global.ssl.fastly.net/media/tvos_radios/wSGYWxvtqZ.jpg",
      location: "Zagreb, Croatia",
      audio: "http://eu10.fastcast4u.com:3180/;stream.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Enter ZG",
      cover:
        "https://pbs.twimg.com/profile_images/1176453483521875969/T3DlnnZr.jpg",
      location: "Zagreb, Croatia",
      audio: "http://live.enterzagreb.hr:8023/;stream.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Gold FM",
      cover: "http://cdn-profiles.tunein.com/s73333/images/logog.png?t=153753",
      location: "Velika Gorica, Croatia",
      audio: "http://live.goldfm.hr:8068/;stream.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Gold (S)EX YU",
      cover:
        "https://mytuner.global.ssl.fastly.net/media/tvos_radios/sncwcuh5tz7w.png",
      location: "Velika Gorica, Croatia",
      audio: "http://c5.hostingcentar.com:8157/;stream.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Dalmacija",
      cover:
        "https://pbs.twimg.com/profile_images/646681406005841920/r9nNVmLM_400x400.png",
      location: "Split, Croatia",
      audio: "http://shoutcast.pondi.hr:8000/;stream.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Extra FM",
      cover:
        "http://www.exyuradio.net/pub/catalog/radio-extra-fm-zagreb-uzivo.jpg",
      location: "Zagreb, Croatia",
      audio: "http://streams.extrafm.hr:8110/stream/1/;stream.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Banovina",
      cover:
        "https://pbs.twimg.com/profile_images/1049304278928711680/9zJE7vob_400x400.jpg",
      location: "Glina, Croatia",
      audio: "http://136.243.21.140:9998/;*.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Istra",
      cover:
        "https://pbs.twimg.com/profile_images/633590203442032640/sO4OYUCL.jpg",
      location: "Pazin, Croatia",
      audio: "http://146.185.18.251:7117/;stream.mp3",
      country: "cro",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Sky Radio 102.5",
      cover:
        "https://dbs.radioline.fr/pictures/radio_70b9621227c3403ae467f7bf30575496/logo200.jpg?size=600",
      location: "Skopje, North Macedonia",
      audio: "http://89.205.123.70:8000/;stream.mp3",
      country: "mkd",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Antenna 5",
      cover:
        "https://static-media.streema.com/media/cache/24/08/240835e3bcd7ce9bc284ce96bea89329.jpg",
      location: "Skopje, North Macedonia",
      audio: "http://antenna5stream.neotel.mk:8000/live64",
      country: "mkd",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Kanal 77",
      cover:
        "http://www.exyuradio.net/pub/catalog/radio-mreza-77-stip-uzivo.jpg",
      location: "Skopje, North Macedonia",
      audio: "http://kanal77.mk:8088/live.mp3",
      country: "mkd",
      id: uuidv4(),
      active: false,
    },
    {
      name: "ZONA M1",
      cover:
        "https://www.uzivoradio.net/wp-content/uploads/2020/05/zona-m1-skopje-1044-600x315.jpg",
      location: "Skopje, North Macedonia",
      audio: "http://89.205.86.241:8000/1",
      country: "mkd",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Ohrid 24 ",
      cover:
        "http://www.balkanradiostanice.com/radio-stanice-logo/radio-ohrid-24-278-makedonija-320.jpg",
      location: "Ohrid, North Macedonia",
      audio: "http://stream.iradio.pro:8146/stream",
      country: "mkd",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Bubamara",
      cover:
        "https://mytuner.global.ssl.fastly.net/media/tvos_radios/jm9NcgwhkP.png",
      location: "Skopje, North Macedonia",
      audio: "http://stream.bubamara.com.mk/live-64.aac",
      country: "mkd",
      id: uuidv4(),
      active: false,
    },
    {
      name: "City Radio 94.7",
      cover: "http://www.predavatel.com/mk/1/skopje_images/sko_city.gif",
      location: "Skopje, North Macedonia",
      audio: "http://176.9.117.123:9998/stream.mp3",
      country: "mkd",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Rrapi Shqip",
      cover:
        "https://rrapi.mk/wp-content/uploads/2019/11/play_kopce_R-300x300.png",
      location: "Struga, North Macedonia",
      audio: "https://stream.zemi.mk:8069/stream",
      country: "mkd",
      id: uuidv4(),
      active: false,
    },

    {
      name: "RSG Sarajevo",
      cover: "https://i1.sndcdn.com/artworks-000143856363-g7phvm-t500x500.jpg",
      location: "Sarajevo , Federation of BiH",
      audio: "http://195.201.112.14:9000/;stream",
      country: "bih",
      id: uuidv4(),
      active: false,
    },

    {
      name: "ANTENA SARAJEVO",
      cover:
        "https://ws.shoutcast.com/images/contacts/6/6830/6830613a-c68e-41cb-8962-f5285543718f/radios/0a69ebb2-cb23-461d-8a2d-a4a03a3c15db/0a69ebb2-cb23-461d-8a2d-a4a03a3c15db.png",
      location: "Sarajevo , Federation of BiH",
      audio: "http://195.201.112.14:9020/;*.mp3",
      country: "bih",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Carsija",
      cover:
        "https://media.radiodeck.com/stations/53b0a7a23004291c2f180000/profile/53b0a7a23004291c2f180000/xl.jpg",
      location: "Sarajevo , Federation of BiH",
      audio: "http://stream.radiocarsija.com:19406/;",
      country: "bih",
      id: uuidv4(),
      active: false,
    },
    {
      name: "BN Radio",
      cover: "https://www.rtvbn.com/site/images/share-default.jpg",
      location: "Bijeljina , RS, BiH",
      audio: "http://stream.rtvbn.com:80/;*.mp3",
      country: "bih",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Big 2",
      cover: "https://cdn-profiles.tunein.com/s70058/images/logog.jpg",
      location: "Banja Luka , RS, BiH",
      audio: "http://big2.bigportal.ba:8100/big2",
      country: "bih",
      id: uuidv4(),
      active: false,
    },
    {
      name: "OTV Valentino",
      cover:
        "https://yt3.ggpht.com/ytc/AAUvwniSCL2ESMfoHjAaqrrMI4x2DyvO8VTFGo9RgnIJ=s900-c-k-c0x00ffffff-no-rj",
      location: "Brcko, BiH",
      audio: " http://77.74.231.19:7109/stream.mp3",
      country: "bih",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio1 Si",
      cover:
        "https://pbs.twimg.com/profile_images/1380218699/Radio_1_400x400.jpg",
      location: "Koper, Slovenia",
      audio: " http://live.radio1.si/Radio1",
      country: "slo",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Aktual",
      cover:
        "https://dpi4fupzvxbqq.cloudfront.net/rfm/uploads/rlogo/300/300_1514581806.jpg",
      location: "Ljubljana, Slovenia",
      audio: "http://195.95.158.131/Aktual",
      country: "slo",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Celje",
      cover: "https://cdn-profiles.tunein.com/s9586/images/logog.jpg",
      location: "Celje, Slovenia",
      audio: "http://stream.rgl.si/Celje",
      country: "slo",
      id: uuidv4(),
      active: false,
    },
    {
      name: "City",
      cover: "https://cdn-radiotime-logos.tunein.com/s16011g.png",
      location: "Maribor, Slovenia",
      audio: "http://82.149.22.34:8000/CityMp364mono.mp3",
      country: "slo",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Rock Radio Si",
      cover:
        "https://static-media.streema.com/media/cache/63/7d/637d72bb401d6e36ff5b45410d5e60eb.jpg",
      location: "Ljubljana, Slovenia",
      audio: "http://stream2.radiocenter.si:9032/;*mp3;",
      country: "slo",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Hit Center",
      cover:
        "https://mediadaily.biz/wp-content/uploads/2019/09/radio-center.png",
      location: "Ljubljana, Slovenia",
      audio: "http://stream3.radiocenter.si:8000/stream.mp3",
      country: "slo",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Veseljak",
      cover:
        "http://www.exyuradio.net/pub/catalog/309-radio-veseljak-uzivo.jpg",
      location: "Ljubljana, Slovenia",
      audio: "http://195.95.158.131/Veseljak",
      country: "slo",
      id: uuidv4(),
      active: false,
    },
    {
      name: "VAL 202",
      cover: "http://www.spletnival.com/datoteke/slike/postaje/val-202.svg",
      location: "Ljubljana, Slovenia",
      audio: "https://mp3.rtvslo.si/val202",
      country: "slo",
      id: uuidv4(),
      active: false,
    },
    {
      name: "TDI Crna Gora",
      cover: "https://cdn-radiotime-logos.tunein.com/s231876g.png",
      location: "Montenegro",
      audio: "http://streaming.tdiradio.com:8000/crnagora.mp3",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Cetinje 94.5",
      cover:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Radio_Cetinje.jpg/1200px-Radio_Cetinje.jpg",
      location: "Montenegro",
      audio: "http://78.129.228.187:8007/stream",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "PLAY MNE",
      cover:
        "https://cdn-profiles.tunein.com/s271769/images/logog.png?t=159128",
      location: "Montenegro",
      audio: "https://stream.playradio.me:8443/play-me.aac",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Tivat",
      cover:
        "https://i2.wp.com/www.radiotivat.com/wp-content/uploads/2019/06/radio-tivat-logo.jpg?fit=200%2C200&ssl=1",
      location: "Montenegro",
      audio: "http://95.211.166.127:8006/stream.mp3",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Budva",
      cover: "http://www.exyuradio.net/pub/catalog/rtb-budva-uzivo.jpg",
      location: "Montenegro",
      audio: "http://listen.shoutcast.com/radiobudva",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio S1 CG",
      cover: "https://www.radios.rs/media/footerlogo/s1.png",
      location: "Montenegro",
      audio: "http://176.9.59.144:8060/;*.mp3",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio S2 CG",
      cover: "https://www.radios.rs/media/footerlogo/s2.png",
      location: "Montenegro",
      audio: "https://stream.radios.rs:9010/stream.mp3",
      country: "mne",
      id: uuidv4(),
      active: false,
    },

    {
      name: "Antena M Podgorica",
      cover: "https://i1.sndcdn.com/avatars-000067822062-089pne-t500x500.jpg",
      location: "Montenegro",
      audio: "http://radioservis.me:8010/antenamlive",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "DRS",
      cover:
        "https://cdn-profiles.tunein.com/s230884/images/logog.jpg?t=152820",
      location: "Montenegro",
      audio: " https://eu2.fastcast4u.com/proxy/mic0?mp=/stream",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Srpski Radio",
      cover: "http://guzei.com/online_radio/logo300/30021.jpg",
      location: "Montenegro",
      audio: "http://188.166.30.166:8000/stream",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
    {
      name: "Radio Mojkovac",
      cover: "https://cdn-radiotime-logos.tunein.com/s211118g.png",
      location: "Montenegro",
      audio: "http://176.9.59.144:8020/stream.mp3",
      country: "mne",
      id: uuidv4(),
      active: false,
    },
  ];
}

export default radioStations;
